import { exec } from "child_process";
import { promises as fs } from "fs";
import path from "path";
import { rimraf } from "rimraf";
import { registry } from "../registry/index";

async function buildRegistryIndex() {
  let index = `/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {`;
  for (const item of registry.items) {
    const resolveFiles = item.files?.map((file) => `registry/${file.path}`);
    if (!resolveFiles) {
      continue;
    }

    const componentPath = item.files?.[0]?.path
      ? `@/registry/${item.files[0].path}`
      : "";

    index += `
  "${item.name}": {
    name: "${item.name}",
    description: "${item.description ?? ""}",
    type: "${item.type}",
    registryDependencies: ${JSON.stringify(item.registryDependencies)},
    files: [${item.files?.map((file) => {
      const filePath = `registry/${typeof file === "string" ? file : file.path}`;
      const resolvedFilePath = path.resolve(filePath);
      return typeof file === "string"
        ? `"${resolvedFilePath}"`
        : `{
      path: "${filePath}",
      type: "${file.type}",
      target: "${file.target ?? ""}"
    }`;
    })}],
    component: ${
      componentPath
        ? `React.lazy(async () => {
      const mod = await import("${componentPath}")
      const exportName = Object.keys(mod).find(key => typeof mod[key] === 'function' || typeof mod[key] === 'object') || item.name
      return { default: mod.default || mod[exportName] }
    })`
        : "null"
    },
    categories: ${JSON.stringify(item.categories)},
    meta: ${JSON.stringify(item.meta)},
  },`;
  }

  index += `
  }`;

  console.log(`#️⃣  ${Object.keys(registry.items).length} components found`);

  // Write style index.
  rimraf.sync(path.join(process.cwd(), "registry/__index__.tsx"));
  await fs.writeFile(path.join(process.cwd(), "registry/__index__.tsx"), index);
}

async function buildRegistryJsonFile() {
  // 1. Fix the path for registry items.
  const fixedRegistry = {
    ...registry,
    items: registry.items.map((item) => {
      const files = item.files?.map((file) => {
        return {
          ...file,
          path: `registry/${file.path}`,
        };
      });

      return {
        ...item,
        files,
      };
    }),
  };

  // 2. Write the content of the registry to `registry.json`
  rimraf.sync(path.join(process.cwd(), `registry.json`));
  await fs.writeFile(
    path.join(process.cwd(), `registry.json`),
    JSON.stringify(fixedRegistry, null, 2),
  );
}

async function buildRegistry() {
  return new Promise((resolve, reject) => {
    const process = exec(
      `bunx shadcn build registry.json --output ../registry/output/`,
      (error, stdout, stderr) => {
        if (error) {
          console.error("Command output:", stdout);
          console.error("Command errors:", stderr);
          reject(new Error(`Process failed: ${error.message}`));
          return;
        }
        console.log(stdout);
        resolve(undefined);
      },
    );

    process.on("exit", (code) => {
      if (code !== 0 && code !== null) {
        console.error(`Process exited with code ${code}`);
      }
    });
  });
}

async function main() {
  try {
    console.log("🗂️ Building registry/__index__.tsx...");
    await buildRegistryIndex();

    console.log("💅 Building registry.json...");
    await buildRegistryJsonFile();

    console.log("🏗️ Building registry...");
    await buildRegistry();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

main();
